### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Varbin** [ox-it/aioldap#1]
Which license does this have? Which conditions must be applied to use it?

**Comment by alexdutton** [comment]
Most things I've written are BSD, but this was a work in process that never went anywhere. I think it's probably best just to use [ldap3](https://pypi.python.org/pypi/ldap3) synchronously, for similar reasons given in http://techspot.zzzeek.org/2015/02/15/asynchronous-python-and-databases/.

**Comment by Varbin** [comment]
Thank you for your fast response. 

But I think when doing multiple LDAP lookups in a single call, synchronous lookups would block the hole (asynchronous program). An SMTP-Servers with user lookup is an example for this. 

Beside from that, you are right.
